// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpI7PwfVaTEEOvJ9-n9DMo7k0-j25GAck',
    appId: '1:678128574139:android:e6065fb5923034d32ed39e',
    messagingSenderId: '678128574139',
    projectId: 'petcentral-e79ae',
    storageBucket: 'petcentral-e79ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg_N8AjrIS9MXTEdUvWie-Hlg52JtvGjw',
    appId: '1:678128574139:ios:75a3a94146cc6f542ed39e',
    messagingSenderId: '678128574139',
    projectId: 'petcentral-e79ae',
    storageBucket: 'petcentral-e79ae.appspot.com',
    androidClientId: '678128574139-t3pqhq0iars8pb1ntaegn473nrrcndtg.apps.googleusercontent.com',
    iosClientId: '678128574139-0muijbltupnq93js3oekv7ui6tfmm49f.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcentralWebAdmin',
  );
}
